name: Update APT Repository

on:
  push:
    paths:
      - 'pool/**/*.deb'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gnupg

      - name: Generate Packages and Release files
        run: |
          mkdir -p dists/stable/main/{binary-amd64,binary-i386,binary-all}
          dpkg-scanpackages --arch all pool/ > dists/stable/main/binary-all/Packages
          dpkg-scanpackages --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
          dpkg-scanpackages --arch i386 pool/ > dists/stable/main/binary-i386/Packages
          gzip -kf dists/stable/main/binary-*/Packages

          rm -f dists/stable/{InRelease,Release,Release.gpg}
          apt-ftparchive release -o APT::FTPArchive::Release::Suite=stable dists/stable > dists/stable/Release

          gpg --default-key "${{ secrets.GPG_EMAIL }}" -abs -o dists/stable/Release.gpg dists/stable/Release

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add dists/
          git commit -m "Update APT repo metadata"
          git push
